/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/intake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Email */
        post: operations["submit_email_v1_intake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dedupe/{quote_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dedupe Quote Request */
        post: operations["dedupe_quote_request_v1_dedupe__quote_request_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Estimate */
        post: operations["create_estimate_v1_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild */
        post: operations["rebuild_v1_graph_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Graph */
        get: operations["search_graph_v1_graph_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/nodes/{node_id}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node Neighbors */
        get: operations["node_neighbors_v1_graph_nodes__node_id__neighbors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph Stats */
        get: operations["graph_stats_v1_graph_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph Schema */
        get: operations["graph_schema_v1_graph_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph Nodes Of Label */
        get: operations["graph_nodes_of_label_v1_graph_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph Full */
        get: operations["graph_full_v1_graph_full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/retrieval/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_v1_retrieval_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/judge/{estimate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Judge Estimate */
        post: operations["judge_estimate_v1_judge__estimate_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_v1_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{review_item_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve */
        post: operations["resolve_v1_review__review_item_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Quotes */
        get: operations["list_all_quotes_v1_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quotes/{quote_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_v1_quotes__quote_request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Adjustment */
        Adjustment: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "substituted" | "added_required" | "discount_removed" | "quantity_assumed";
            /** Sku Id */
            sku_id?: string | null;
            /** Detail */
            detail: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Route */
            route: string;
            /** Rule */
            rule: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
        };
        /** DedupeResponse */
        DedupeResponse: {
            /**
             * Quote Request Id
             * Format: uuid
             */
            quote_request_id: string;
            /** Verdicts */
            verdicts: components["schemas"]["DedupeVerdictResponse"][];
        };
        /** DedupeVerdictResponse */
        DedupeVerdictResponse: {
            /**
             * Candidate Quote Request Id
             * Format: uuid
             */
            candidate_quote_request_id: string;
            /** Verdict */
            verdict: string;
            /** Content Jaccard */
            content_jaccard: number;
            /** Style Jaccard */
            style_jaccard: number;
            /** Signals Fired */
            signals_fired: string[];
        };
        /** DimensionScore */
        DimensionScore: {
            /**
             * Name
             * @enum {string}
             */
            name: "contract_discount" | "graph_completion" | "price_provenance";
            /** Score */
            score: number;
            /** Rationale */
            rationale: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            }[];
        };
        /** DraftLine */
        DraftLine: {
            /** Sku Id */
            sku_id?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Unit Price */
            unit_price?: number | null;
            /** Price Source */
            price_source?: ("list" | "predicted") | null;
            /**
             * Discount Pct
             * @default 0
             */
            discount_pct: number;
        };
        /** EstimateDraft */
        EstimateDraft: {
            /** Customer Id */
            customer_id?: string | null;
            /** Contract Id */
            contract_id?: string | null;
            /** Lines */
            lines: components["schemas"]["DraftLine"][];
            /** Adjustments */
            adjustments?: components["schemas"]["Adjustment"][];
            /** Flags */
            flags?: string[];
        };
        /** EstimateRequest */
        EstimateRequest: {
            /**
             * Quote Request Id
             * Format: uuid
             */
            quote_request_id: string;
            /** As Of */
            as_of?: string | null;
        };
        /** EstimateResponse */
        EstimateResponse: {
            /**
             * Estimate Id
             * Format: uuid
             */
            estimate_id: string;
            /**
             * Quote Request Id
             * Format: uuid
             */
            quote_request_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "needs_review";
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            draft: components["schemas"]["EstimateDraft"] | null;
            totals: components["schemas"]["Totals"] | null;
            /** Violations */
            violations: components["schemas"]["Violation"][];
            /** Iterations */
            iterations: number;
            /** Reason */
            reason: string | null;
        };
        /** FullGraphResponse */
        FullGraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Community */
            community: number | null;
        };
        /** GraphStatsResponse */
        GraphStatsResponse: {
            /** Node Counts */
            node_counts: {
                [key: string]: number;
            };
            /** Edge Counts */
            edge_counts: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntakeRequest */
        IntakeRequest: {
            /** Email Text */
            email_text: string;
        };
        /** IntakeResponse */
        IntakeResponse: {
            /**
             * Quote Request Id
             * Format: uuid
             */
            quote_request_id: string;
            /** Customer Id */
            customer_id: string | null;
            /** Site Id */
            site_id: string | null;
            /** Contract Id */
            contract_id: string | null;
            /** Line Items */
            line_items: components["schemas"]["LineItemResponse"][];
        };
        /** JudgeResponse */
        JudgeResponse: {
            /**
             * Judge Verdict Id
             * Format: uuid
             */
            judge_verdict_id: string;
            /**
             * Estimate Id
             * Format: uuid
             */
            estimate_id: string;
            /** Model */
            model: string;
            /** Dimensions */
            dimensions: components["schemas"]["DimensionScore"][];
            /** Overall Confidence */
            overall_confidence: number;
            /** Flagged Dimension */
            flagged_dimension: string;
            /** Trusted */
            trusted: boolean;
            review_item: components["schemas"]["ReviewItemResponse"] | null;
        };
        /** LabelNodesResponse */
        LabelNodesResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Truncated */
            truncated: boolean;
        };
        /** LineItemResponse */
        LineItemResponse: {
            /** Sku Name As Written */
            sku_name_as_written: string;
            /** Sku Id */
            sku_id: string | null;
            /** Quantity */
            quantity: string | null;
        };
        /** MetricCountsResponse */
        MetricCountsResponse: {
            /** Verdicts Total */
            verdicts_total: number;
            /** Verdicts Trusted */
            verdicts_trusted: number;
            /** Review Items Resolved */
            review_items_resolved: number;
            /** Review Items Corrected */
            review_items_corrected: number;
            /** Requests Compared */
            requests_compared: number;
            /** Requests Duplicate */
            requests_duplicate: number;
            /** Flags By Dimension */
            flags_by_dimension: {
                [key: string]: number;
            };
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Auto Send Rate */
            auto_send_rate: number | null;
            /** Correction Rate */
            correction_rate: number | null;
            /** Duplicate Rate */
            duplicate_rate: number | null;
            counts: components["schemas"]["MetricCountsResponse"];
        };
        /** NeighborhoodResponse */
        NeighborhoodResponse: {
            center: components["schemas"]["GraphNode"];
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Truncated */
            truncated: boolean;
        };
        /** QuoteDedupeVerdictResponse */
        QuoteDedupeVerdictResponse: {
            /**
             * Candidate Quote Request Id
             * Format: uuid
             */
            candidate_quote_request_id: string;
            /** Verdict */
            verdict: string;
            /** Content Jaccard */
            content_jaccard: number;
            /** Style Jaccard */
            style_jaccard: number;
            /** Signals Fired */
            signals_fired: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuoteDetailResponse */
        QuoteDetailResponse: {
            /**
             * Quote Request Id
             * Format: uuid
             */
            quote_request_id: string;
            /** Case Id */
            case_id: string | null;
            /** Customer Id */
            customer_id: string | null;
            /** Site Id */
            site_id: string | null;
            /** Contract Id */
            contract_id: string | null;
            /** Raw Email Text */
            raw_email_text: string;
            /** Parsed Json */
            parsed_json: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dedupe Verdicts */
            dedupe_verdicts: components["schemas"]["QuoteDedupeVerdictResponse"][];
            /** Estimates */
            estimates: components["schemas"]["QuoteEstimateResponse"][];
            /** Skus */
            skus: {
                [key: string]: components["schemas"]["QuoteSkuInfoResponse"];
            };
        };
        /** QuoteEstimateResponse */
        QuoteEstimateResponse: {
            /**
             * Estimate Id
             * Format: uuid
             */
            estimate_id: string;
            /** Status */
            status: string;
            draft: components["schemas"]["EstimateDraft"] | null;
            totals: components["schemas"]["Totals"] | null;
            /** Violations */
            violations: components["schemas"]["Violation"][];
            /** Iterations */
            iterations: number;
            /** Reason */
            reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            judge_verdict: components["schemas"]["QuoteJudgeVerdictResponse"] | null;
            /** Review Items */
            review_items: components["schemas"]["QuoteReviewItemResponse"][];
        };
        /** QuoteJudgeVerdictResponse */
        QuoteJudgeVerdictResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model */
            model: string;
            /** Dimensions */
            dimensions: components["schemas"]["DimensionScore"][];
            /** Overall Confidence */
            overall_confidence: number;
            /** Flagged Dimension */
            flagged_dimension: string;
            /** Trusted */
            trusted: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuoteReviewItemResponse */
        QuoteReviewItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Dimension */
            dimension: string;
            /** Fact */
            fact: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Line Index */
            line_index: number | null;
            /** Status */
            status: string;
            /** Outcome */
            outcome: string | null;
            /** Correction */
            correction: {
                [key: string]: unknown;
            } | null;
            /** Resolved At */
            resolved_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuoteSkuInfoResponse */
        QuoteSkuInfoResponse: {
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Discontinued */
            discontinued: boolean;
        };
        /** QuoteSummaryResponse */
        QuoteSummaryResponse: {
            /**
             * Quote Request Id
             * Format: uuid
             */
            quote_request_id: string;
            /** Case Id */
            case_id: string | null;
            /** Customer Id */
            customer_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Estimate Count */
            estimate_count: number;
            /** Latest Estimate Status */
            latest_estimate_status: string | null;
            /** Latest Trusted */
            latest_trusted: boolean | null;
            /** Open Review Items */
            open_review_items: number;
            /** Is Duplicate */
            is_duplicate: boolean;
        };
        /** RebuildResponse */
        RebuildResponse: {
            /** Namespace */
            namespace: string;
            /** Fingerprint */
            fingerprint: string;
            /** Node Counts */
            node_counts: {
                [key: string]: number;
            };
            /** Edge Counts */
            edge_counts: {
                [key: string]: number;
            };
            /** Community Count */
            community_count: number;
            /** Largest Community Size */
            largest_community_size: number;
        };
        /** ResolveReviewItemRequest */
        ResolveReviewItemRequest: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "approved" | "corrected";
            /** Correction */
            correction?: {
                [key: string]: unknown;
            } | null;
        };
        /** ResolveReviewItemResponse */
        ResolveReviewItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Outcome */
            outcome: string;
            /** Correction */
            correction: {
                [key: string]: unknown;
            } | null;
            /** Consolidation Enqueued */
            consolidation_enqueued: boolean;
        };
        /** ReviewItemListResponse */
        ReviewItemListResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Estimate Id
             * Format: uuid
             */
            estimate_id: string;
            /**
             * Quote Request Id
             * Format: uuid
             */
            quote_request_id: string;
            /** Dimension */
            dimension: string;
            /** Fact */
            fact: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Line Index */
            line_index: number | null;
            /** Status */
            status: string;
            /** Outcome */
            outcome: string | null;
            /** Correction */
            correction: {
                [key: string]: unknown;
            } | null;
            /** Resolved At */
            resolved_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReviewItemResponse */
        ReviewItemResponse: {
            /** Dimension */
            dimension: string;
            /** Fact */
            fact: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Line Index */
            line_index: number | null;
        };
        /** SchemaEdge */
        SchemaEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Count */
            count: number;
        };
        /** SchemaOverviewResponse */
        SchemaOverviewResponse: {
            /** Node Counts */
            node_counts: {
                [key: string]: number;
            };
            /** Edges */
            edges: components["schemas"]["SchemaEdge"][];
        };
        /** Totals */
        Totals: {
            /** List Total */
            list_total: number;
            /** Discount Total */
            discount_total: number;
            /** Net Total */
            net_total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Violation */
        Violation: {
            /** Guardrail */
            guardrail: string;
            /** Line Index */
            line_index?: number | null;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit_email_v1_intake_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dedupe_quote_request_v1_dedupe__quote_request_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_estimate_v1_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_v1_graph_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RebuildResponse"];
                };
            };
        };
    };
    search_graph_v1_graph_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    node_neighbors_v1_graph_nodes__node_id__neighbors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_stats_v1_graph_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphStatsResponse"];
                };
            };
        };
    };
    graph_schema_v1_graph_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaOverviewResponse"];
                };
            };
        };
    };
    graph_nodes_of_label_v1_graph_nodes_get: {
        parameters: {
            query: {
                label: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelNodesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_full_v1_graph_full_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FullGraphResponse"];
                };
            };
        };
    };
    ask_v1_retrieval_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    judge_estimate_v1_judge__estimate_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                estimate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_v1_review_get: {
        parameters: {
            query?: {
                status?: "open" | "resolved" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemListResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_v1_review__review_item_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveReviewItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveReviewItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_quotes_v1_quotes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteSummaryResponse"][];
                };
            };
        };
    };
    get_quote_v1_quotes__quote_request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
}
